import { test, expect, type Page } from '@playwright/test';
import { expectAccessible, tokenColor } from './contracts';
async function state(page:Page,name:string){
 await page.getByRole('button',{name:'UI preview',exact:true}).click();
 await page.getByRole('menuitemcheckbox',{name,exact:true}).click();
}
test('input pointer focus is quiet and fresh file action preserves context',async({page})=>{
 await page.goto('/');
 const field=page.getByRole('textbox',{name:/Draft for/});
 await field.click();
 await expect(page.locator('.work-composer')).toHaveCSS('border-top-color',await tokenColor(page,'control-border-hover'));
 await expect(page.locator('.work-composer')).toHaveCSS('border-bottom-color',await tokenColor(page,'focus-ring'));
 const size=await page.locator('.work-composer').boundingBox();
 await field.click();
 expect((await page.locator('.work-composer').boundingBox())?.height).toEqual(size?.height);
 const picker=page.waitForEvent('filechooser');
 await page.getByRole('button',{name:'Start from a file…',exact:true}).click();
 await (await picker).setFiles({name:'brief.md',mimeType:'text/markdown',buffer:Buffer.from('A local briefing')});
 await expect(page.getByRole('button',{name:'Inspect brief.md'})).toBeVisible();
 await expect(field).toHaveValue('');
 await expectAccessible(page);
});
test('background tabs keep state and hover exposes stable title, latest section and recorded time',async({page})=>{
 await page.clock.install();await page.goto('/');
 await state(page,'Preview working state');
 let first=page.getByRole('tab',{name:'New conversation',exact:true});
 await expect(first.getByRole('img',{name:'Working · sample',exact:true})).toBeVisible();
 await expect(first).toHaveAttribute('aria-selected','true');
 await expect(first.locator('..')).toHaveCSS('box-shadow','none');
 await expect(first.locator('..')).toHaveCSS('border-bottom-left-radius','0px');
 await first.hover();
 await expect(first).toHaveCSS('background-color','rgba(0, 0, 0, 0)');
 const fullTitle='Q4 pricing research — competitor tiers, usage estimates and customer positioning';
 await first.click({button:'right'});
 await page.getByRole('menuitem',{name:'Rename tab',exact:true}).click();
 await page.getByRole('textbox',{name:'Name',exact:true}).fill(fullTitle);
 await page.getByRole('button',{name:'Save',exact:true}).click();
 first=page.getByRole('tab',{name:fullTitle,exact:true});
 await page.getByRole('button',{name:'New tab',exact:true}).first().click();
 const second=page.getByRole('tab',{name:'New conversation 2',exact:true});
 await expect(second).toHaveAttribute('aria-selected','true');
 await expect(first).toHaveAttribute('aria-selected','false');
 await state(page,'Preview decision state');
 await expect(second.getByRole('img',{name:'Needs your input · sample',exact:true})).toBeVisible();
 await expect(first.getByRole('img',{name:'Working · sample',exact:true})).toBeVisible();
 await page.clock.fastForward(120000);
 await first.hover();
 await page.clock.fastForward(1000);
 const preview=page.getByRole('tooltip');
 await expect(preview).toContainText(fullTitle);
 await expect(preview).toContainText('Price bands in EUR');
 await expect(preview).toContainText('2 minutes ago');
 await expect(preview.locator('p')).toHaveCount(3);
 await expect(preview).not.toContainText('Latest section:');
 await expect(second).toHaveAttribute('aria-selected','true');
 await page.reload();
 await expect(first.getByRole('img',{name:'Working · sample',exact:true})).toBeVisible();
 await expect(second.getByRole('img',{name:'Needs your input · sample',exact:true})).toBeVisible();
 await expectAccessible(page);
});
test('receiving, failure and retry samples preserve work and an unsent draft',async({page})=>{
 await page.goto('/');await state(page,'Preview receiving reply');
 const draft=page.getByRole('textbox',{name:/Draft for/});
 await draft.fill('Keep this instruction');
 await expect(page.locator('.work-output[aria-busy=true]')).toHaveCount(1);
 await expect(page.getByRole('tab',{name:'New conversation',exact:true}).getByRole('img',{name:'Receiving reply · sample',exact:true})).toBeVisible();
 await expect(page.locator('.work-composer-caption')).toContainText('type to steer');
 await state(page,'Preview failed state');
 await expect(draft).toHaveValue('Keep this instruction');
 await expect(page.getByText('Sample request failed · your draft and partial result are kept')).toBeVisible();
 await expectAccessible(page);
 await page.getByRole('button',{name:'Retry sample',exact:true}).click();
 await expect(draft).toHaveValue('Keep this instruction');
 await expect(page.getByRole('button',{name:'Stop',exact:true})).toBeVisible();
 await state(page,'Preview completed state');
 await expect(page.getByRole('tab',{name:'New conversation',exact:true}).getByRole('img',{name:'Completed · sample',exact:true})).toBeVisible();
 await expect(page.getByRole('tab').getByRole('img',{name:'Completed · sample',exact:true})).toHaveCSS('color',await tokenColor(page,'muted'));
 await expect(page.getByRole('button',{name:'Stop',exact:true})).not.toBeVisible();
 await expect(draft).toHaveValue('Keep this instruction');
 await expectAccessible(page);
});
