import { readFileSync } from 'node:fs';
export const design = JSON.parse(readFileSync(new URL('../src/design/tokens.json', import.meta.url), 'utf8'));
const declarations = values => Object.entries(values).map(([key, value]) => `  --${key}: ${value};`).join('\n');
// Colour roles that read the tint (--h, --a) or another role are re-declared on every [data-tint]
// container, so a space tint set on any element recomputes them there, as in the designer's foundations.
const derived = values => Object.fromEntries(Object.entries(values).filter(([, value]) => value.includes('var(--')));
const tint = ({ h, a, swatch }) => `--h: ${h}; --a: ${a}; --swatch: ${swatch};`;
const tints = Object.entries(design.tints.hues).map(([name, hue]) => `[data-tint="${name}"] { ${tint(hue)} }`).join('\n');
const dark = `  color-scheme: dark;\n${declarations(design.themes.dark)}`;
// Reduced motion also covers component durations and new motion distances as tokens are added.
// i2-banner-duration stays: the banner drops its 8px slide and keeps the 200ms fade (NB-3).
const reducedMotion = Object.keys(design.foundation).flatMap(key => {
 if ((key.startsWith('dur') || key.endsWith('-duration') || key === 'motion-tab-collapse') && key !== 'duration-none' && key !== 'i2-banner-duration') return [`--${key}: var(--duration-none);`];
 if (key.startsWith('motion-scale-') && key !== 'motion-scale-rest') return [`--${key}: var(--motion-scale-rest);`];
 if (key.startsWith('motion-rise-') || ['motion-travel', 'motion-directional-travel', 'motion-place-slide', 'breathe-from', 'breathe-to'].includes(key)) return [`--${key}: var(--motion-rest);`];
 return [];
}).join(' ');
export const css = `/* Generated by npm run design:generate. Edit src/design/tokens.json. */
:root {
  color-scheme: light;
  ${tint(design.tints.hues[design.tints.default])}
${declarations(design.foundation)}
${declarations(design.themes.light)}
}
${tints}
[data-tint] {
${declarations(derived(design.themes.light))}
}
:root[data-theme="dark"], :root[data-theme="dark"] [data-tint] {
${dark}
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]):not([data-theme="dark"]), :root:not([data-theme="light"]):not([data-theme="dark"]) [data-tint] {
${dark}
  }
}
/* Explicit nested appearances let specimens compare both palettes inside either app theme. */
:root [data-theme="light"], :root [data-theme="light"][data-tint] {
  color-scheme: light;
${declarations(design.themes.light)}
}
:root [data-theme="dark"], :root [data-theme="dark"][data-tint] {
${dark}
}
@media (prefers-reduced-motion: reduce) {
  :root { ${reducedMotion} }
}
`;
const b = design.brand;
const mark = `<path d="${b.path}" fill="none" stroke="${b.foreground}" stroke-width="${b.strokeWidth}" stroke-linecap="round"/>`;
export const brandSvg = `<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="${b.viewBox}"><rect width="64" height="64" rx="${b.tileRadius}" fill="${b.background}"/>${mark}</svg>\n`;
export const maskSvg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${b.viewBox}"><path d="${b.path}" fill="none" stroke="#000" stroke-width="${b.strokeWidth}" stroke-linecap="round"/></svg>\n`;
export const generatedFiles = {
 'src/styles/tokens.css': css,
 'public/favicon.svg': brandSvg,
 'public/mask-icon.svg': maskSvg,
 'src-tauri/icons/source.svg': brandSvg,
 'index.html': readFileSync(new URL('../src/design/index.template.html', import.meta.url), 'utf8')
   .replaceAll('{{canvas-light}}', design.themes.light['chrome-canvas'])
   .replaceAll('{{canvas-dark}}', design.themes.dark['chrome-canvas'])
   .replaceAll('{{brand-background}}', design.brand.background),
};

// Native window geometry follows the same foundation; unrelated Tauri settings remain native-owned.
for (const path of ['src-tauri/tauri.conf.json', 'src-tauri/tauri.macos.conf.json']) {
 const config = JSON.parse(readFileSync(new URL(`../${path}`, import.meta.url), 'utf8'));
 const { trafficLightPosition, ...geometry } = design.nativeWindow;
 config.app.windows = config.app.windows.map(window => window.label === 'main'
  ? { ...window, ...geometry, ...(path.includes('macos') ? { trafficLightPosition } : {}) } : window);
 generatedFiles[path] = JSON.stringify(config, null, 2) + '\n';
}
