import { readFileSync } from 'node:fs';
export const design = JSON.parse(readFileSync(new URL('../src/design/tokens.json', import.meta.url), 'utf8'));
const declarations = values => Object.entries(values).map(([key, value]) => `  --${key}: ${value};`).join('\n');
const dark = `  color-scheme: dark;\n${declarations(design.themes.dark)}`;
export const css = `/* Generated by npm run design:generate. Edit src/design/tokens.json. */
:root {
  color-scheme: light;
${declarations(design.foundation)}
${declarations(design.themes.light)}
}
:root[data-theme="dark"] {
${dark}
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]):not([data-theme="dark"]) {
${dark}
  }
}
@media (prefers-reduced-motion: reduce) {
  :root { --duration: var(--duration-none); }
}
`;
const b = design.brand;
const mark = `<path d="${b.path}" fill="none" stroke="${b.foreground}" stroke-width="${b.strokeWidth}" stroke-linecap="round"/>`;
export const brandSvg = `<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="${b.viewBox}"><rect width="64" height="64" rx="${b.tileRadius}" fill="${b.background}"/>${mark}</svg>\n`;
export const maskSvg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${b.viewBox}"><path d="${b.path}" fill="none" stroke="#000" stroke-width="${b.strokeWidth}" stroke-linecap="round"/></svg>\n`;
export const generatedFiles = {
 'src/styles/tokens.css': css,
 'public/favicon.svg': brandSvg,
 'public/mask-icon.svg': maskSvg,
 'src-tauri/icons/source.svg': brandSvg,
 'index.html': readFileSync(new URL('../src/design/index.template.html', import.meta.url), 'utf8')
   .replaceAll('{{canvas-light}}', design.themes.light.canvas)
   .replaceAll('{{canvas-dark}}', design.themes.dark.canvas)
   .replaceAll('{{brand-background}}', design.brand.background),
};

// Native window geometry follows the same foundation; unrelated Tauri settings remain native-owned.
for (const path of ['src-tauri/tauri.conf.json', 'src-tauri/tauri.macos.conf.json']) {
 const config = JSON.parse(readFileSync(new URL(`../${path}`, import.meta.url), 'utf8'));
 const { trafficLightPosition, ...geometry } = design.nativeWindow;
 config.app.windows = config.app.windows.map(window => window.label === 'main'
  ? { ...window, ...geometry, ...(path.includes('macos') ? { trafficLightPosition } : {}) } : window);
 generatedFiles[path] = JSON.stringify(config, null, 2) + '\n';
}
