#!/usr/bin/env python3
"""Pair every captured frame with its `-after` twin into one gallery page.

A ledger row closes on a before/after pair and on nothing else, so the pairing
has to be mechanical: a lane names its new capture `<name>-after.<w>x<h>.txt`
beside the `<name>.<w>x<h>.txt` the audit was written from, and this walks the
directory and finds them. A frame with no twin is listed too, under what it is —
either a surface nobody has fixed yet, or a surface that was already right.
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
FRAMES = ROOT / "docs/design/polish/frames"
SIZE = re.compile(r"^(?P<name>.+?)\.(?P<w>\d+)x(?P<h>\d+)\.txt$")

# The four sizes every surface is judged at, widest first, so a gallery row
# reads the way a person resizes a window: from all the room there is down to
# the floor a terminal is allowed to be.
ORDER = [(160, 50), (120, 40), (80, 24), (60, 30)]


def main() -> int:
    pairs: dict[str, dict[tuple[int, int], pathlib.Path]] = {}
    for f in sorted(FRAMES.glob("*.txt")):
        m = SIZE.match(f.name)
        if not m:
            continue
        pairs.setdefault(m["name"], {})[(int(m["w"]), int(m["h"]))] = f

    out = [
        "# The gallery",
        "",
        "Generated by `scripts/gallery.py`. Every row is one surface at one size,",
        "with the frame the audit was written from and the frame that closed it.",
        "Both are plain text captured off the real binary in a real terminal, and",
        "each has a `.ans` twin beside it carrying the colour.",
        "",
    ]
    fixed, only = [], []
    for name in sorted(pairs):
        if name.endswith("-after"):
            continue
        after = pairs.get(name + "-after")
        (fixed if after else only).append(name)

    out += ["## before and after", ""]
    if fixed:
        out += ["| surface | size | before | after |", "| --- | --- | --- | --- |"]
        for name in fixed:
            for size in ORDER:
                b = pairs[name].get(size)
                a = pairs[name + "-after"].get(size)
                if not (b and a):
                    continue
                out.append(
                    f"| `{name}` | {size[0]}x{size[1]} "
                    f"| [before](frames/{b.name}) | [after](frames/{a.name}) |"
                )
    else:
        out.append("Nothing has closed on a pair yet.")

    out += ["", "## captured, not yet changed", "",
            "Either a surface no lane has reached, or one the audit found already right.",
            ""]
    for name in only:
        sizes = " · ".join(f"[{w}x{h}](frames/{pairs[name][(w, h)].name})"
                           for w, h in ORDER if (w, h) in pairs[name])
        out.append(f"- `{name}` — {sizes or 'no standard size'}")

    (FRAMES.parent / "GALLERY.md").write_text("\n".join(out) + "\n")
    print(f"docs/design/polish/GALLERY.md — {len(fixed)} surfaces paired, {len(only)} not yet")
    return 0


if __name__ == "__main__":
    sys.exit(main())
