#!/usr/bin/env python3
"""Assemble docs/design/polish/LEDGER.md from the per-surface audits beside it.

The audits are where a defect is written down in full: what it is, the line
that decides it, why it costs a developer something, the fix shape, the
severity and the frames it was seen on. The ledger is the one ORDERED list the
owner reads, so it is GENERATED from them and never edited by hand — an edit
here would be a second copy of a number that is already written down somewhere
else, and a second copy is a copy that will drift.

A row CLOSES when the audit that holds it names its number under `## fixed`,
which is the same thing as saying it closes on a captured before/after pair,
because that is what a lane has to put there. The spellings below are the ones
the lanes actually write — a table row, a bolded number, a `Row N` heading —
and a spelling nobody uses is not worth matching.
"""

import datetime
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
D = ROOT / "docs/design/polish"

# One letter per surface, so a row can be named in a commit message or across a
# desk ("H3", "C12") without saying which file it came out of.
PREFIX = {
    "home": "H", "tasks": "T", "cli": "C", "help": "P",
    "chat": "K", "settings": "S", "commands": "M", "jobs": "J",
}

ROW = re.compile(r"^(\d+)\. (.*)$")
SEV = re.compile(r"sev: (high|med|low)")
# How a lane says "this row is done", in the three shapes they write.
CLOSED = [
    re.compile(r"^\|\s*(\d+)\s*\|", re.M),          # a table row
    re.compile(r"[Rr]ow\s+(\d+)\b"),                 # "Row 7 — …"
    re.compile(r"\*\*([\d,\s]+)\*\*"),               # "**1, 2, 11, 23**"
]


def closed_rows(text: str) -> set[str]:
    found: set[str] = set()
    for pattern in CLOSED:
        for hit in pattern.findall(text):
            found.update(re.findall(r"\d+", hit))
    return found


def main() -> int:
    out = [
        "# The polish ledger",
        "",
        "Generated by `scripts/ledger.py` from the per-surface audits beside it —",
        "do not edit this file. Each row is `<id> <severity> <state> — what it is`,",
        "and the audit named in the heading carries the line it lives on, why it",
        "costs a developer something, the fix shape and the frames it was seen on.",
        "",
        "A row closes on a captured before/after pair and on nothing else.",
        "",
        f"_{datetime.datetime.now(datetime.UTC):%Y-%m-%d %H:%MZ}_",
        "",
    ]
    tally = {"open": 0, "CLOSED": 0}
    for path in sorted(D.glob("audit-*.md")):
        surface = path.stem[len("audit-"):]
        p = PREFIX.get(surface, surface[:1].upper())
        body = path.read_text()
        head, _, fixed = body.partition("\n## fixed")
        done = closed_rows(fixed) if fixed else set()

        out += [f"## {surface} — [{path.name}]({path.name})", ""]
        for line in head.splitlines():
            m = ROW.match(line)
            if not m:
                continue
            n, rest = m.group(1), m.group(2)
            what = rest.split(" — ", 1)[0]
            sev = SEV.search(line)
            state = "CLOSED" if n in done else "open"
            tally[state] += 1
            out.append(f"- `{p}{n}`".ljust(9) + f" {sev.group(1) if sev else '?':<5}{state:<7}{what}")
        out.append("")

    (D / "LEDGER.md").write_text("\n".join(out) + "\n")
    print(f"{D.relative_to(ROOT)}/LEDGER.md — {tally['open']} open, {tally['CLOSED']} closed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
