#!/usr/bin/env bash
# ledger.sh — assemble docs/design/polish/LEDGER.md from the per-surface audits.
#
# The audits are where a defect is written down in full: what, where, why it
# costs a developer something, the fix shape, the severity and the frames. The
# ledger is the one ORDERED list the owner reads, so it is generated from them
# and never edited by hand — an edit here would be a second copy of a number
# that is already written down somewhere else.
#
# A row closes when the audit that holds it names its number under `## fixed`,
# which is the same thing as saying it closes on a captured before/after pair,
# because that is what a lane has to put there.
set -euo pipefail
cd "$(dirname "$0")/.."
D=docs/design/polish

{
  echo '# The polish ledger'
  echo
  echo 'Generated by `scripts/ledger.sh` from the per-surface audits beside it —'
  echo 'do not edit this file. Each row is `<id> <severity> — what it is`, and the'
  echo 'audit named in the heading carries the line it lives on, why it costs a'
  echo 'developer something, the fix shape and the frames it was seen on.'
  echo
  printf '_%s_\n' "$(date -u '+%Y-%m-%d %H:%MZ')"
  echo
  for f in "$D"/audit-*.md; do
    surface=$(basename "$f" .md); surface=${surface#audit-}
    case $surface in
      home) p=H ;; tasks) p=T ;; cli) p=C ;; help) p=P ;;
      chat) p=K ;; settings) p=S ;; *) p=$(echo "$surface" | cut -c1 | tr a-z A-Z) ;;
    esac
    fixed=$(sed -n '/^## fixed/,$p' "$f" || true)
    echo "## $surface — [$(basename "$f")]($(basename "$f"))"
    echo
    awk -v p="$p" -v fixed="$fixed" '
      /^[0-9]+\. / {
        n = $0; sub(/\. .*/, "", n)
        what = $0; sub(/^[0-9]+\. /, "", what)
        # the WHAT is everything before the first em-dash separator.
        i = index(what, " — "); if (i > 0) what = substr(what, 1, i - 1)
        sev = "?"
        if (match($0, /sev: [a-z]+/)) sev = substr($0, RSTART + 5, RLENGTH - 5)
        mark = "open"
        if (fixed ~ ("(^|\n)[-*] ?" p n "\\b") || fixed ~ ("(^|\n)" n "\\. ")) mark = "CLOSED"
        printf "- `%s%-2s` %-4s %-6s %s\n", p, n, sev, mark, what
      }
    ' "$f"
    echo
  done
} > "$D/LEDGER.md"

open=$(grep -c ' open ' "$D/LEDGER.md" || true)
closed=$(grep -c ' CLOSED ' "$D/LEDGER.md" || true)
echo "$D/LEDGER.md — $open open, $closed closed"
