package atlas

// Pairing is the map of the two-computer pairing feature, grounded in the
// code. Each Files[].Path must exist relative to the repository root;
// data_test.go checks that for every registered map.
var Pairing = &Map{
	Name:        "pairing",
	Title:       "Pairing",
	Description: "codeaf on two computers: pair with a link, continue a chat on the other",
	Nodes: []Node{
		// ── machines ──────────────────────────────────────────────────────
		{ID: "machineA", Label: "Machine A", Short: "existing device", Kind: KindMachine, X: 0.08, Y: 0.1,
			Summary: "The computer that already runs codeaf. It approves new machines and publishes each chat's turns so another machine can continue them.",
			Details: []string{"Holds the identity key and a device cert signed by it", "Publishes encrypted frames every turn while it holds the chat's lease"},
			Files: []FileRef{
				{Path: "cmd/codeaf/approvals.go", Symbols: []string{"approvalsDoor"}},
				{Path: "cmd/codeaf/syncdrive.go", Symbols: []string{"startDrive"}, Note: "starts the drive side: publishes turns while this machine holds the lease"},
			}},
		{ID: "machineB", Label: "Machine B", Short: "new device", Kind: KindMachine, X: 0.92, Y: 0.1,
			Summary: "The computer being added. It runs `codeaf pair`, and once joined it can 'continue here' on a chat that is running on A.",
			Details: []string{"Generates its own ed25519 device key and x25519 box key", "Plaintext files only ever exist on the machines, never on the relay"},
			Files:   []FileRef{{Path: "cmd/codeaf/pair.go", Symbols: []string{"runPair"}}}},
		// ── services ──────────────────────────────────────────────────────
		{ID: "hosted", Label: "hosted relay", Short: "default", Kind: KindService, X: 0.38, Y: 0.1,
			Summary: "The default service at https://codeaf.agentfield.ai/fabric: a Cloudflare Worker with Durable Objects and R2. It holds the directory, the encrypted blobs and pairing requests, and it cannot decrypt any of them.",
			Details: []string{
				"Limits: 5 GiB/identity, 1200 req/min/identity, 600/min/device",
				"Pairing: 10-minute TTL, 10 link creates/hr, 3 pending per IP",
				"Keeps no request log and no account table: an identity is the hash of its key",
			},
			Files: []FileRef{
				{Path: "relay/hosted/src/limits.js", Symbols: []string{"DEFAULTS"}},
				{Path: "relay/hosted/src/routes.js"},
				{Path: "internal/syncsetup/relayurl.go", Symbols: []string{"HostedRelayURL"}},
			}},
		{ID: "selfrelay", Label: "codeaf relay", Short: "self-hosted", Kind: KindService, X: 0.62, Y: 0.1,
			Summary: "The same service, self-hosted: `codeaf relay` or cmd/relay. It keeps one SQLite directory and one blob folder per identity, logs only ids and byte counts, and forwards remote-engine bytes without reading them.",
			Details: []string{
				"Routes /v1/dir/, /v1/identity/, /v1/store/, the link path, the pair mailbox, /v1/engine, /status",
				"Flags --listen :8787 --store --trust-proxy; no TLS or quota built in",
				"Selected with CODEAF_SYNC_URL=<url> (or off)",
			},
			Files: []FileRef{
				{Path: "cmd/relay/main.go", Symbols: []string{"main"}},
				{Path: "internal/relayserve/main.go", Symbols: []string{"Main"}},
				{Path: "internal/relayserve/service.go"},
				{Path: "internal/relayserve/namespaces.go"},
				{Path: "internal/relay/relay.go", Note: "blind pipe for a live remote engine"},
				{Path: "docs/relay.md"},
			}},
		// ── codeaf Go ─────────────────────────────────────────────────────
		{ID: "pair", Label: "pair", Short: "link + 4 digits", Kind: KindGo, X: 0.1, Y: 0.38,
			Summary: "`codeaf pair` on the new machine prints a link and a 4-digit check. The existing machine pastes the link into the chat (the pairing card opens) or runs `codeaf pair approve`, the person compares the digits and answers a. No account is involved.",
			Details: []string{
				"check = the first two bytes of sha256(pubkey) read as one number, mod 10000, so a swapped key shows different digits",
				"Link key k lives only in the URL fragment and seals the device name",
				"The grant is sealed to B's x25519 key, so the relay only sees an opaque box",
			},
			Files: []FileRef{
				{Path: "cmd/codeaf/pair.go", Symbols: []string{"pairDoor", "runPair"}},
				{Path: "cmd/codeaf/pairlink.go", Symbols: []string{"askToJoin", "approve", "linkApprover", "homeSigner"}},
				{Path: "cmd/codeaf/pairroute.go", Symbols: []string{"pairMailbox", "pairGrant"}},
				{Path: "cmd/codeaf/pair_terminal.go"},
				{Path: "internal/pair/linkjoin.go", Symbols: []string{"JoinByLink", "awaitDecision"}},
				{Path: "internal/pair/linkapprove.go", Symbols: []string{"Approver.Look", "Approver.Approve"}},
				{Path: "internal/pair/linkkey.go", Symbols: []string{"NewLinkKey", "SealDeviceName"}},
				{Path: "internal/pair/linkgrant.go", Symbols: []string{"LinkGrant", "openLinkGrant"}},
				{Path: "internal/directory/requests.go"},
			}},
		{ID: "identity", Label: "identity", Short: "keys + certs", Kind: KindGo, X: 0.3, Y: 0.38,
			Summary: "One identity key per person signs a cert for each device. Every request a device makes is signed with ed25519. Rotation mints a new identity and re-issues the devices.",
			Files: []FileRef{
				{Path: "cmd/codeaf/identity.go", Symbols: []string{"identityDoor", "runIdentity"}},
				{Path: "cmd/codeaf/identity_rotate.go", Symbols: []string{"identityRotate", "confirmRotation"}},
				{Path: "internal/identity/device.go", Symbols: []string{"Cert.Verify", "Dev.Sign"}},
				{Path: "internal/identity/rotation.go", Symbols: []string{"Mint", "NewDevice", "Install"}},
			}},
		{ID: "devices", Label: "devices", Short: "/devices", Kind: KindGo, X: 0.1, Y: 0.65,
			Summary: "`codeaf devices` and /devices list devices and show which are online. You can revoke or rename one. The relay refuses a revoked device, and the other devices hear about it through the directory watch.",
			Files: []FileRef{
				{Path: "cmd/codeaf/devices.go", Symbols: []string{"runDevices", "listDevices", "stopDevice"}},
				{Path: "cmd/codeaf/devrename.go", Symbols: []string{"renameThisDevice", "tellFleet"}},
				{Path: "internal/directory/presence.go"},
			}},
		{ID: "sync", Label: "sync", Short: "syncsetup", Kind: KindGo, X: 0.55, Y: 0.38,
			Summary: "Opens the connection to the relay, signs requests, seals the vault with chacha20poly1305, follows the directory (\"running on A\"), and runs Continuer.Take for 'continue here'.",
			Files: []FileRef{
				{Path: "cmd/codeaf/syncwire.go", Symbols: []string{"syncOf", "syncFrom"}},
				{Path: "cmd/codeaf/synctake.go", Symbols: []string{"wireSync", "watchStanding"}},
				{Path: "cmd/codeaf/syncdrive.go", Symbols: []string{"startDrive"}},
				{Path: "internal/syncsetup/syncsetup.go", Symbols: []string{"Sync", "Open", "Follow"}},
				{Path: "internal/syncsetup/drive.go", Symbols: []string{"Drive", "syncVault"}},
				{Path: "internal/syncsetup/take.go", Symbols: []string{"Continuer.Take", "restoreCopies", "pullVault"}},
				{Path: "internal/keys/seal.go", Symbols: []string{"seal", "open"}},
			}},
		{ID: "cells", Label: "cells", Short: "continue here", Kind: KindGo, X: 0.8, Y: 0.38,
			Summary: "A cell is a chat together with its workspace. On by default; CODEAF_CELLS=0 turns cells off. 'Continue here' on home moves the files, history, tool output and task records to this machine.",
			Details: []string{"do_continue.go continues a `do` run on the same machine; it does not move anything between machines"},
			Files: []FileRef{
				{Path: "cmd/codeaf/cell.go", Symbols: []string{"runCell", "cellRewind", "cellEngine"}},
				{Path: "cmd/codeaf/cell_list.go", Symbols: []string{"cellList"}},
				{Path: "cmd/codeaf/do_cell.go", Symbols: []string{"errandCell"}},
				{Path: "cmd/codeaf/do_continue.go", Symbols: []string{"readPriorRun", "continuationBrief"}},
				{Path: "internal/tui3/homepanel_continue.go"},
				{Path: "internal/handoff/handoff.go", Symbols: []string{"Taker.Take", "keepLocal", "fetchAndAcquire", "install"}},
				{Path: "docs/testing-anywhere.md"},
			}},
		{ID: "cellsync", Label: "cellsync", Short: "frames up/down", Kind: KindGo, X: 0.55, Y: 0.65,
			Summary: "Moves encrypted frames. On the machine that holds the chat it seals each turn, exports and uploads the frames, then moves the head. On the machine that takes over it fetches the missing frames.",
			Files: []FileRef{
				{Path: "internal/cellsync/publish.go", Symbols: []string{"Publisher.Publish", "Publisher.Upload"}},
				{Path: "internal/cellsync/batch.go", Symbols: []string{"Publishing.Seal", "Batcher.lost"}},
				{Path: "internal/cellsync/fetch.go", Symbols: []string{"Fetcher.Fetch", "Fetcher.Complete"}},
				{Path: "internal/cellsync/branch.go", Symbols: []string{"Brancher.Branch"}},
			}},
		{ID: "cellstore", Label: "cellstore", Short: "Go → furrow", Kind: KindGo, X: 0.3, Y: 0.65,
			Summary: "The Go driver for the Rust engine. It talks to the engine as a subprocess or through a unix-socket daemon (there is no FFI). It tries the daemon first and falls back to running `furrow` once per verb. It records each tool call in a WAL and seals afterwards.",
			Details: []string{
				"Daemon: `furrow serve --socket S --idle-minutes N`; the socket file lives in codeaf's home as engine-<ver>-<hash>.sock",
				"Spawn: `furrow --json export --head H --outbox O --ledger L`",
				"Keys are passed through env FURROW_CELL_KEY / FURROW_DEDUP_SECRET",
			},
			Files: []FileRef{
				{Path: "internal/cellstore/transport.go", Symbols: []string{"Transport", "Fallback", "Spawn"}},
				{Path: "internal/cellstore/daemon.go", Symbols: []string{"Daemon.Do"}},
				{Path: "internal/cellstore/daemonstart.go", Symbols: []string{"launch"}},
				{Path: "internal/cellstore/engine.go", Symbols: []string{"Engine.Seal"}},
				{Path: "internal/cellstore/syncops.go", Symbols: []string{"SyncEngine.Export", "SyncKeys"}},
				{Path: "internal/cellstore/recorder.go", Symbols: []string{"Recorder"}},
				{Path: "internal/cellstore/wal.go"},
				{Path: "internal/cellstore/rewind.go", Symbols: []string{"Engine.Rewind"}},
				{Path: "internal/furrow/furrow.go", Symbols: []string{"ResolveOwned"}},
			}},
		// ── furrow (Rust) ─────────────────────────────────────────────────
		{ID: "furrowDaemon", Label: "furrow-daemon", Short: "unix socket", Kind: KindEngine, X: 0.2, Y: 0.9,
			Summary: "A long-lived engine process. It reads one JSON request per line on a unix socket, uses one writer thread per store, and handles 9 verbs: seal, snap, restore, log, export, published, want, import, materialize.",
			Files: []FileRef{
				{Path: "engine/furrow-daemon/src/server.rs"},
				{Path: "engine/furrow-daemon/src/wire.rs", Symbols: []string{"Request", "Response", "parse_request"}},
				{Path: "engine/furrow-daemon/src/router.rs", Symbols: []string{"Router"}},
				{Path: "engine/furrow-daemon/src/verbs.rs", Symbols: []string{"lookup"}},
			}},
		{ID: "furrowCli", Label: "furrow-cli", Short: "`furrow` binary", Kind: KindEngine, X: 0.45, Y: 0.9,
			Summary: "The `furrow` command. The exchange verbs export, published, want, import and materialize take --json, and so do timeline, rewind, merge and serve; `furrow fork COMMAND` runs a command in the new fork and refuses --json there.",
			Files: []FileRef{
				{Path: "engine/furrow-cli/src/main.rs"},
				{Path: "engine/furrow-cli/src/exchange.rs", Symbols: []string{"run"}},
				{Path: "engine/README.md"},
			}},
		{ID: "furrowCore", Label: "furrow-core", Short: "CoW + timeline", Kind: KindEngine, X: 0.72, Y: 0.9,
			Summary: "The engine library. It forks workspaces with copy-on-write (APFS clonefile, Linux FICLONE), splits files into content-defined BLAKE3 chunks in hash-verified packs, and keeps a Merkle timeline with rewind. Frames sent to another machine are encrypted with XChaCha20-Poly1305.",
			Files: []FileRef{
				{Path: "engine/furrow-core/src/repository.rs", Symbols: []string{"FurrowRepository.seal", "FurrowRepository.fork", "FurrowRepository.rewind"}},
				{Path: "engine/furrow-core/src/fork.rs", Symbols: []string{"fork_workspace"}},
				{Path: "engine/furrow-core/src/chunker.rs"},
				{Path: "engine/furrow-core/src/store.rs"},
				{Path: "engine/furrow-core/src/remote_crypto.rs", Symbols: []string{"encrypt_object", "decrypt_object"}},
				{Path: "engine/furrow-core/src/exchange/export.rs", Symbols: []string{"run"}},
				{Path: "engine/furrow-core/src/exchange/fetch.rs", Symbols: []string{"want"}},
				{Path: "engine/furrow-core/src/exchange/materialize.rs", Symbols: []string{"materialize"}},
				{Path: "engine/furrow-core/src/exchange/keys.rs"},
			}},
		{ID: "spec", Label: "specs", Short: "ux + testing", Kind: KindSpec, X: 0.92, Y: 0.65,
			Summary: "The written contracts: how pairing must look and behave, and how to test 'anywhere' end to end.",
			Files: []FileRef{
				{Path: "docs/ux-pairing-contract.md"},
				{Path: "docs/testing-anywhere.md"},
			}},
	},
	Edges: []Edge{
		{ID: "a-pair", From: "machineA", To: "pair", Label: "approve link", Detail: "Paste the link into the chat (`/pair <link>` or a paste opens the card) or run `codeaf pair approve LINK`."},
		{ID: "b-pair", From: "machineB", To: "pair", Label: "codeaf pair"},
		{ID: "pair-hosted", From: "pair", To: "hosted", Label: "link request", Detail: "POST /v1/link/requests; the device name is sealed under the link key; the grant is a sealed box."},
		{ID: "pair-identity", From: "pair", To: "identity", Label: "cert + grant"},
		{ID: "devices-hosted", From: "devices", To: "hosted", Label: "presence/revoke", Detail: "GET /v1/dir/presence; revocation is written to the directory, signed."},
		{ID: "a-devices", From: "machineA", To: "devices", Label: "/devices"},
		{ID: "identity-sync", From: "identity", To: "sync", Label: "signs requests", Detail: "ed25519 device cert via wireauth."},
		{ID: "sync-hosted", From: "sync", To: "hosted", Label: "/v1/dir + store", Detail: "Signed requests. Only ciphertext and directory rows cross."},
		{ID: "sync-self", From: "sync", To: "selfrelay", Label: "CODEAF_SYNC_URL"},
		{ID: "b-cells", From: "machineB", To: "cells", Label: "continue here"},
		{ID: "cells-sync", From: "cells", To: "sync", Label: "Continuer.Take"},
		{ID: "cells-cellsync", From: "cells", To: "cellsync", Label: "fetch + acquire"},
		{ID: "cellsync-hosted", From: "cellsync", To: "hosted", Label: "encrypted frames", Detail: "Frames are XChaCha20-Poly1305 ciphertext; the relay never sees plaintext."},
		{ID: "cellsync-cellstore", From: "cellsync", To: "cellstore", Label: "export/want/import"},
		{ID: "cellstore-daemon", From: "cellstore", To: "furrowDaemon", Label: "unix socket JSON", Detail: "One JSON object per line; tried first."},
		{ID: "cellstore-cli", From: "cellstore", To: "furrowCli", Label: "exec per verb", Detail: "Fallback when the daemon is not reachable."},
		{ID: "daemon-core", From: "furrowDaemon", To: "furrowCore", Label: "FurrowRepository"},
		{ID: "cli-core", From: "furrowCli", To: "furrowCore", Label: "FurrowRepository"},
		{ID: "spec-pair", From: "spec", To: "cells", Label: "specifies"},
	},
	Flows: []Flow{
		{ID: "pairing", Title: "Pairing", Summary: "Add machine B with a link and a 4-digit check. No account is needed. The relay only sees sealed boxes.", Steps: []Step{
			{From: "machineB", To: "pair", Message: "`codeaf pair`: make an ed25519 device key, an x25519 box key and a 16-byte link key k", Edge: "b-pair", Note: "internal/pair/linkkey.go NewLinkKey"},
			{From: "pair", To: "hosted", Message: "POST /v1/link/requests {pubkey, x25519, name_sealed, check}", Edge: "pair-hosted"},
			{From: "hosted", To: "pair", Message: "code (8 chars, 10 min TTL); B prints URL code#k and the 4 digits", Edge: "pair-hosted"},
			{From: "machineA", To: "pair", Message: "the person pastes the link into the chat (the pairing card opens) or runs `codeaf pair approve`", Edge: "a-pair"},
			{From: "pair", To: "hosted", Message: "A: GET /v1/link/requests/{code}, open the name with k, show name and digits", Edge: "pair-hosted", Note: "Approver.Look"},
			{From: "machineA", To: "pair", Message: "the person checks the 4 digits match on both screens and answers the card: a approves, d denies (`codeaf pair approve` asks y/n)", Edge: "a-pair"},
			{From: "pair", To: "identity", Message: "A signs a cert for B's key; the grant is sealed to B's x25519 key", Edge: "pair-identity"},
			{From: "pair", To: "hosted", Message: "POST /v1/dir/requests/{code}/approve (signed); relay writes the Device record", Edge: "pair-hosted"},
			{From: "hosted", To: "machineB", Message: "awaitDecision gets the grant; openLinkGrant installs identity, cert and SyncURL", Note: "single use: a second approver gets 409"},
		}},
		{ID: "continue", Title: "Continue chat", Summary: "Machine B takes over a chat running on A: workspace, history, tool output and task records.", Steps: []Step{
			{From: "machineB", To: "cells", Message: "home shows 'running on A'; the person picks continue here", Edge: "b-cells", Note: "internal/tui3/homepanel_continue.go"},
			{From: "cells", To: "sync", Message: "syncsetup's Continuer.Take runs the takeover (internal/handoff): B's own unsealed edits are sealed into a branch first, then the lease moves", Edge: "cells-sync"},
			{From: "sync", To: "hosted", Message: "Dir.Cell(id): read head, frame list and lease", Edge: "sync-hosted"},
			{From: "cells", To: "cellsync", Message: "keepLocal: B's own edits are sealed and kept as a branch", Edge: "cells-cellsync"},
			{From: "cellsync", To: "cellstore", Message: "furrow `want --head H` lists the missing frames", Edge: "cellsync-cellstore"},
			{From: "hosted", To: "cellsync", Message: "download the encrypted frames into the inbox", Edge: "cellsync-hosted"},
			{From: "sync", To: "hosted", Message: "Dir.Acquire: new lease and fence; A loses the drive (Batcher.lost)", Edge: "sync-hosted"},
			{From: "cellstore", To: "furrowDaemon", Message: "import (verify + decrypt), then materialize --head into a stage", Edge: "cellstore-daemon"},
			{From: "sync", To: "machineB", Message: "restoreCopies, pullVault, restoreChatFiles; the chat opens on B, and B now publishes"},
		}},
		{ID: "furrow", Title: "Furrow seal → fork → materialize", Summary: "How a turn becomes encrypted frames that another machine turns back into an identical workspace.", Steps: []Step{
			{From: "cellstore", To: "cellstore", Message: "Recorder writes the call's intent to the WAL, runs it, writes completion", Note: "internal/cellstore/recorder.go, wal.go"},
			{From: "cellstore", To: "furrowDaemon", Message: "Engine.Seal: a seal request as one JSON line on the unix socket", Edge: "cellstore-daemon"},
			{From: "furrowDaemon", To: "furrowCore", Message: "FurrowRepository::seal: BLAKE3 chunks → packs → Merkle tree → snapshot id", Edge: "daemon-core"},
			{From: "furrowCli", To: "furrowCore", Message: "fork: fork_workspace clones copy-on-write (clonefile / FICLONE)", Edge: "cli-core"},
			{From: "cellsync", To: "cellstore", Message: "export --head H --outbox O --ledger L (key in FURROW_CELL_KEY)", Edge: "cellsync-cellstore"},
			{From: "cellsync", To: "hosted", Message: "upload XChaCha20-Poly1305 frames; furrow `published` updates the ledger", Edge: "cellsync-hosted"},
			{From: "hosted", To: "cellsync", Message: "on B: want, then download the missing frames", Edge: "cellsync-hosted"},
			{From: "cellstore", To: "furrowCli", Message: "import, then `materialize --head H`: writes a byte-exact workspace", Edge: "cellstore-cli"},
		}},
	},
}
